### ISSUE TITLE
How to show LSP's diagnostic error code

### ISSUE THREAD

**Issue by andrejcesen** [rafaeldelboni/cajus-nvim#21]
Great work on opening up a config using fennel :)

Seeing your examples, I was wondering how did you display LSP's diagnostic error code as shown here:

<img width="881" alt="Screen Shot 2023-07-19 at 15 34 11" src="https://github.com/rafaeldelboni/cajus-nvim/assets/1460733/4743626a-4e53-4da2-89c9-5d173fd46c9d">

Cheers

**Comment by rafaeldelboni** [comment]
The error code shown is pretty much the default settings, but sometimes it doesn't show, maybe because the warning is derived from kondo, I don't know for sure. 
<img width="472" alt="image" src="https://github.com/rafaeldelboni/cajus-nvim/assets/1683898/0ceda6fd-2c19-4f40-9bd7-ba6d7b54bd48">

**Comment by andrejcesen** [comment]
Gotcha, thanks! In the end I used the global `vim.diagnostic.config()` API

```
(vim.diagnostic.config {:float {:format (fn [diagnostic] 
                                              (string.format "%s [%s]"
                                                             diagnostic.message
                                                             diagnostic.code))}})
```
